before_script:
  - . ~/.nvm/nvm.sh
  - nvm use 8.9.4

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy_desarrollo:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rsync -rlDv --delete dist /software/base/frontend
  environment:
    name: desarrollo
    url: ciriscr.com
  only:
  - desarrollo
