before_script:
  - . ~/.nvm/nvm.sh
  - nvm use 8.9.4

stages:
  - test
  - deploy

lintear:
  stage: test
  script:
    - npm install
    - npm run lint

deploy_desarrollo:
  stage: deploy
  script:
    - npm install
    - npm run stage
    - rsync -rlDv --delete dist/ /software/trakapp/frontend/
  environment:
    name: desarrollo
    url: trakapp.ciriscr.com
  only:
  - desarrollo

deploy_estable:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rsync -rlDv --delete dist/ /software/trakapp/produccion/admin
  environment:
    name: estable
    url: https://admin.trakapp.co.cr
  only:
  - estable
